### ISSUE TITLE
Write some docs

### ISSUE THREAD

**Issue by jamadden** [NextThought/nti.fakestatsd#1]
Carefully decide what needs to be public and documented, and where it should live.

**Comment by cutz** [comment]
I was thinking some about what should be exposed last night. I'm considering moving towards a single object that encapsulates a Metric, instead of the metric specific subclasses that currently exist, and then providing some hamcrest matchers for aiding in assertions about the metrics.  The primary documented API then becomes `FakeStatsDClient`, `Metric`, and a set of hamcrest convenience matchers.  Thoughts?

**Comment by jamadden** [comment]
Works for me.

**Comment by jamadden** [comment]
Fixed in #9
