### ISSUE TITLE
Matchers should accept the same type of parameters as the StatsdClient methods

### ISSUE THREAD

**Issue by jamadden** [NextThought/nti.fakestatsd#15]
For example, I shouldn't have to specify a string in the matcher when I specify an int to the client.

This example should pass; that it doesn't, and that the output really doesn't show why, is confusing:
```pycon
In [1]: from  nti.fakestatsd import FakeStatsDClient

In [2]: test_client = FakeStatsDClient()

In [3]: test_client.gauge('active_sessions', 320)

In [4]: from hamcrest import assert_that, contains

In [5]: from nti.fakestatsd.matchers import is_gauge

In [6]: assert_that(test_client,
   ...:     contains(is_gauge('active_sessions', 320)))
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
...
AssertionError:
Expected: a sequence containing [Metric of form <active_sessions:320|g>]
     but: item 0: was <active_sessions:320|g>
```

(That's the example from the documentation, which passes if you write `is_gauge('active_sessions', '320')`)

**Comment by cutz** [comment]
This is something I had similar thoughts/concerns with in terms of the ``value`` provided on ``Metric``. It's always a string even if you give perfmetrics a number.  In terms of the actual statsd format there are legitimate cases for value to be a string not an number.  For example, [Gauges](https://github.com/etsy/statsd/blob/master/docs/metric_types.md#gauges) can be given a string of the format ``+n`` or ``-n`` to increment or decrement the gauge rather than set it.

It would be nice if the value you passed to perfmetrics carried through to the value in the Metric object that gets collected.

Perhaps that's another argument for not collecting these packets at the socket layer and rather implementing the metric tracking by overriding each of the public functions.

**Comment by cutz** [comment]
It's worth nothing that while perfmetrics doesn't explicit document the relative gauge values, it would work if you passed a string as the value to ``gauge``  instead of a number.

**Comment by jamadden** [comment]
So would it just work if the matcher called `str` on the argument?
